/**
 * @file buffer.h
 * @brief Declarations for buffer structures and functions used to parse,
 *        store, sort, and process U.S. ZIP code CSV data, including
 *        length-indicated records and header operations.
 *
 * Gives the core data structures and function declarations
 * used throughout the ZIP Code File Processing assignment.
 */

#ifndef BUFFER_H
#define BUFFER_H

#include <iostream>
#include <string>
#include <fstream>
#include <sstream>
#include <vector>
#include <map>

using namespace std;

/**
 * @struct buffer
 * @brief Represents one ZIP code record loaded from a CSV or length-indicated file.
 *
 * This structure stores all fields required for ZIP code processing.
 * It is populated by parsing functions and passed through sorting
 * and record-generation functions.
 *
 * @var buffer::zip
 *      The 5-digit ZIP code (stored as unsigned int).
 *
 * @var buffer::length
 *      The length of the CSV or length-indicated record line.
 *
 * @var buffer::place_name
 *      City or town name associated with the ZIP code.
 *
 * @var buffer::state
 *      Two-character state abbreviation (e.g., "NY").
 *
 * @var buffer::county
 *      The county name associated with the ZIP code.
 *
 * @var buffer::latitude
 *      Geographic latitude coordinate.
 *
 * @var buffer::longitude
 *      Geographic longitude coordinate.
 *
 * @var buffer::tempString
 *      A reusable temporary string buffer for conversions (CSV parsing).
 *
 * @var buffer::padding
 *      One padding byte included for alignment/safety.
 */
typedef struct 
{ 
    unsigned int zip; 
    unsigned int length;
    string place_name; 
    string state;
    string county; 
    double latitude; 
    double longitude; 
    string tempString = ",";
    char padding[1]; 
} buffer;

/**
 * @brief Parses a CSV file into buffer records and writes output to a text file.
 *
 * @param argc Argument count.
 * @param argv Argument vector.
 * @param pointer Pointer to a buffer struct to store each parsed record.
 * @param file Name of the input CSV file.
 * @param txtFile Output file stream for storing parsed data.
 */
void parsing(int argc, char** argv, buffer* pointer, string file, ofstream& txtFile);

/**
 * @brief Creates formatted output files from a CSV input file.
 *
 * This may include sorting, organizing, or formatting ZIP records.
 *
 * @param argc Argument count.
 * @param argv Argument vector.
 * @param pointer Pointer to a buffer struct.
 * @param file Input CSV filename.
 */
void createFiles(int argc, char** argv, buffer* pointer, string file);

/**
 * @brief Sorts ZIP code records numerically by ZIP code.
 *
 * @param records Vector of buffer records to be sorted.
 */
void sortingZip(vector<buffer>& records);

/**
 * @brief Sorts ZIP code records geographically (e.g., latitude/longitude).
 *
 * @param records Vector of buffer records to be sorted.
 */
void sortingLocation(vector<buffer>& records);

/**
 * @brief Reads an entire length-indicated ZIP code file into memory.
 *
 * @param filename Name of the length-indicated file.
 * @param records Vector to store all unpacked buffer records.
 */
void readLengthIndicatedFile(string filename, vector<buffer>& records);

/**
 * @brief Converts one line from a length-indicated file into a buffer record.
 *
 * @param line One full length-indicated record line.
 * @param record Output buffer struct to fill.
 * @return true if the unpacking succeeds; false otherwise.
 */
bool unpackRecord(string line, buffer& record);

/**
 * @brief Generates a table of state-based geographic extremes.
 *
 * For each state, finds:
 *  - Easternmost ZIP (min longitude)
 *  - Westernmost ZIP (max longitude)
 *  - Northernmost ZIP (max latitude)
 *  - Southernmost ZIP (min latitude)
 *
 * @param records Vector of ZIP code records.
 */
void generateStateTable(vector<buffer>& records);

/**
 * @brief Prints the state table previously generated by generateStateTable().
 */
void printStateTable();

/**
 * @brief Reads a specific record from a file based on byte offset.
 *
 * Useful for random-access reading in length-indicated files.
 *
 * @param filename Input filename.
 * @param offset Byte position where the record begins.
 * @param outRecord Output record to populate.
 * @return true if read succeeds; false if EOF or failure.
 */
bool readRecordAtOffset(const std::string& filename, std::streampos offset, buffer& outRecord);

/**
 * @brief Writes a header record line to a file.
 *
 * This is used for generating the length-indicated file’s header block.
 *
 * @param outStream Output file stream.
 * @param headerText Header data to write as a single line.
 */
void writeHeaderRecord(std::ofstream& outStream, const std::string& headerText);


/**
 * @brief Reads the header line from a length-indicated file.
 *
 * @param inStream Input file stream.
 * @param outHeader The resulting header line read from the file.
 * @return true if header exists and was read; false otherwise.
 */
bool readHeaderLine(std::ifstream& inStream, std::string& outHeader);

#endif